pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                // sh 'mvn -B -DskipTests clean package'
                echo 'Build done'
            }
        }
        stage('Deliver') {
            steps {
                // sh './jenkins/scripts/deliver.sh'
                echo 'Delivery done'
            }
        }
        stage('Complete') {
            steps {
                echo 'Build is completed OK JTM'
            }
        }
    }
}
